name: Python application

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install pytest-cov
        pip install codecov
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run pytest libpythonpro --cov=libpythonpro
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: '7f7cbfe5-1300-4b79-8c70-5e6514c12eac'
      run: |
        codecov